# Generated by Django 4.0.2 on 2022-02-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='dataUpdated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='dateCreated',
        ),
        migrations.AlterField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(default=0, verbose_name='Count In Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short Description'),
        ),
    ]
