# Generated by Django 4.0.2 on 2022-02-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
