# Generated by Django 4.0.2 on 2022-02-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_product_thumbnail_product_imagefour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dataUpdated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('shipping_cost', models.IntegerField(verbose_name='shipping cost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
