# Generated by Django 4.0.1 on 2022-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_rename_quantity_product_countinstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(default=0, verbose_name='count in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
